### PR TITLE
Set up ci with azure-pipelines

### PR DESCRIPTION
**Pull request by huiyifyj**
Upload azure-pipelines.yml file to set up CI with Azure Pipelines.

### CODE REVIEW

**Comment by huiyifyj** [comment]
Azure Pipelines can't use `scoop` command, although it run installing scripts.
```powershell
iwr -useb get.scoop.sh | iex
```

And the output log display error.
Error

The pwsh start with some args
Screen2

So, it is recommended to use `GitHub Actions` instead of `Azure Pipelines`.

**Comment by Pengxn** [comment]
Indeed, screenshots display azure-pipelines can't run it normally.
You can new branch to use `Github Action`.

**Review by Pengxn — COMMENTED** [review]
Close the pr, if you have no objection.

**Comment by Pengxn** [comment]
> Screen2

You can solve it by using `##vso[task.prependpath]$PATH`.
More information to [azure-pipelines-tasks#Logging Commands](https://github.com/microsoft/azure-pipelines-tasks/blob/45387862227b0c888818fad22cba7594287d7574/docs/authoring/commands.md#task-logging-commands), or [stackoverflow#Cannot change the PATH in a script task in Azure Pipelines](https://stackoverflow.com/questions/52631143/cannot-change-the-path-in-a-script-task-in-azure-pipelines).

Please new a PR to try it if you more spare time.

**Comment by huiyifyj** [comment]
> > Screen2
> 
> You can solve it by using `##vso[task.prependpath]$PATH`.
> More information to [azure-pipelines-tasks#Logging Commands](https://github.com/microsoft/azure-pipelines-tasks/blob/45387862227b0c888818fad22cba7594287d7574/docs/authoring/commands.md#task-logging-commands), or [stackoverflow#Cannot change the PATH in a script task in Azure Pipelines](https://stackoverflow.com/questions/52631143/cannot-change-the-path-in-a-script-task-in-azure-pipelines).
> 
> Please new a PR to try it if you more spare time.

👌

**Pull request closed without merging**
